services:
  site:
    build:
      context: .
      target: development
    ports:
      - "4321:4321"
    volumes:
      - ./src:/site/src
      - ./public:/site/public
      - ./astro.config.mjs:/site/astro.config.mjs:ro
      - ./tsconfig.json:/site/tsconfig.json:ro
    environment:
      CHOKIDAR_USEPOLLING: "true"
      ASTRO_TELEMETRY_DISABLED: "1"
